#ifndef ESCAPE_H
#define ESCAPE_H

#define TO_STR_H(str) #str
#define TO_STR(str) TO_STR_H(str)

#define ESC_SEQ "\x1b["
#define ESC(c) ESC_SEQ c

#define ESC_HIDE_CURSOR ESC("?25l")
#define ESC_SHOW_CURSOR ESC("?25h")

#define ESC_CLEAR_SCREEN ESC("2J")
#define ESC_CLEAR_LINE ESC("2K")

//#define ESC_FULL_CLEAR ESC("c")   // THIS IS BROKEN DO NOT USE

#define ESC_MOVE_TO_AUX_BUFFER  ESC("?1049h")
#define ESC_MOVE_TO_MAIN_BUFFER ESC("?1049l")
#define ESC_ENABLE_MOUSE_TRACKING ESC("?1000h")
#define ESC_DISABLE_MOUSE_TRACKING ESC("?1000l")


/* Text attributes */
#define ESC_INVERTED_TEXT_COLOR ESC("7m")
#define ESC_RESET_TEXT_ATTRIBUTES ESC("m")

#define ESC_BACKGROUND_COLOR_RED ESC("41m")
#define ESC_RESET_BACKGROUND_ATTRIBUTES ESC("0m")

#define ESC_TEXT_BOLD ESC("1m")
#define ESC_TEXT_RESET_BOLD ESC("22m")

#define ESC_RESET_CURSOR_POSSITION ESC("0;0H")
#define ESC_MOVE_CURSOR_LEFT ESC("1D")
#define ESC_MOVE_CURSOR_RIGHT ESC("1C")
#define ESC_MOVE_CURSOR_DOWN ESC("1B")
#define ESC_MOVE_CURSOR_UP ESC("1A")

/* Cursor */
#define ESC_DISABLE_CURSOR_BLINKING ("?12l")

#endif